language: c

compiler:
    - clang
    - gcc

jobs:
  include:
    - os: linux
      disk: bionic
      env: MBEDTLS=1
    - os: linux
      dist: xenial
      env: MBEDTLS=1
    - os: linux
      dist: trusty
    - os: osx

env:
    global:
        - PATH="/usr/bin:/usr/local/bin:$PATH"

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq libfuse-dev ruby-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ -z "$MBEDTLS" ]; then sudo apt-get install -qq libmbedtls-dev; else sudo apt-get install -qq libpolarssl-dev; fi 
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install -v Caskroom/cask/osxfuse; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./src/mbed_install.sh; fi

install:
    - cmake .
    - make VERBOSE=1
    - sudo make install

script:
    - make travis-test

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
